language: cpp

sudo: required

compiler: 
  - gcc
  - clang

before_install:
  - source .travis/setup_travis.sh

script:
  - source .travis/build.sh

notifications:
  email:
    on_failure: always
    on_success: change

