
set( INDENT "[****] ")

string(TOLOWER ${PROJECT_NAME} LOWER_PROJECT_NAME)

set (GENEIAL_SHARED_SUFFIX "_shared")
set (LIB_GENEIAL_SHARED_NAME "${LOWER_PROJECT_NAME}${GENEIAL_SHARED_SUFFIX}")

set (GENEIAL_STATIC_SUFFIX "_static")
set (LIB_GENEIAL_STATIC_NAME "${LOWER_PROJECT_NAME}${GENEIAL_STATIC_SUFFIX}")