#
# GENEIAL Version information
#
set (GENEIAL_VERSION_MAJOR 0)
set (GENEIAL_VERSION_MINOR 2)
set (GENEIAL_VERSION_PATCH 0)


#SO name str
set(GENEIAL_VERSION_STRING ${GENEIAL_VERSION_MAJOR}.${GENEIAL_VERSION_MINOR}.${GENEIAL_VERSION_PATCH})
