/*--------------------------------------------------------------------------
 * libGeneiAL - metadata & runtime configuration file.
 * This file is AUTOMATICALLY GENERATED from Config.h.in. 
 * If you need to make changes edit the original file NOT THIS FILE.
 * --------------------------------------------------------------------------*/

#pragma once

// the configured options and settings for geneial
#define GENEIAL_VERSION_MAJOR @GENEIAL_VERSION_MAJOR@
#define GENEIAL_VERSION_MINOR @GENEIAL_VERSION_MINOR@
#define GENEIAL_VERSION_PATCH @GENEIAL_VERSION_PATCH@
#define GENEIAL_VERSION_STRING "@GENEIAL_VERSION_STRING@"

#define GENEIAL_BUILD_TYPE "@CMAKE_BUILD_TYPE@"

#define GENEIAL_BRANCH "@GIT_BRANCH@"
#define GENEIAL_COMMIT "@GIT_COMMIT_HASH@"
